
dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: Install System Packages
  command: |
    sudo apt update -qq
    sudo apt install -y python-pip

version: 2.1

executors:
  content-executor:
    docker:
      - image: circleci/python:3.7.7
    working_directory: ~/repo

jobs:
  validate-content:
    executor: content-executor
    steps:
      - run:
          name: Checkout Repository
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/diogofgm/${CIRCLE_PROJECT_REPONAME}
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/diogofgm/${CIRCLE_PROJECT_REPONAME}
            fi
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "TA-ibm_datapower/src/TA-ibm_datapower/default/app.conf" }}
      - run: *apt-install
      - run:
          name: Get Splunk AppInspect CLI
          command: |
            curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o appinspect-lastest.tar.gz 
            mkdir appinspect-latest
            tar -zxvf appinspect-lastest.tar.gz -C appinspect-latest --strip-components=1
      - run:
          name: Install Splunk AppInspect CLI
          command: |
            cd appinspect-latest
            rm -rf venv
            sudo pip install --upgrade pip setuptools
            sudo pip install virtualenv
            virtualenv --clear venv
            source venv/bin/activate
            pip install .
      - run:
          name: Run Splunk AppInspect
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}/src
            tar -zcvf ${CIRCLE_PROJECT_REPONAME}.tar.gz ${CIRCLE_PROJECT_REPONAME}
            mkdir ../dist
            cp ${CIRCLE_PROJECT_REPONAME}.tar.gz ../dist/
            cd ../../
            cd appinspect-latest
            pwd
            ls -ltr
            source venv/bin/activate
            splunk-appinspect inspect ../${CIRCLE_PROJECT_REPONAME}/src/${CIRCLE_PROJECT_REPONAME}.tar.gz | tee appinspect.log
            if grep -q FAILURE "appinspect.log"; then
              exit 1
            fi
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "TA-ibm_datapower/src/TA-ibm_datapower/default/app.conf" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: TA-ibm_datapower/dist/
          paths:
              - TA-ibm_datapower.tar.gz
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/TA-ibm_datapower/dist/TA-ibm_datapower.tar.gz
      - run:
          name: Publish release on Github
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/${CIRCLE_PROJECT_REPONAME}/dist/${CIRCLE_PROJECT_REPONAME}.tar.gz
  publish-splunkbase-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/TA-ibm_datapower/dist/TA-ibm_datapower.tar.gz
      - run:
          name: Login to Splunkbase
          command: |
            AUTH=$(curl --location --request POST 'https://splunkbase.splunk.com/api/account:login/' --data-urlencode 'username='"$SPLUNKBASE_USER"'' --data-urlencode 'password='"$SPLUNKBASE_PASSWORD"'')
            echo "$AUTH" > login.xml
            if [ "$AUTH" == "Credentials Invalid" ]; then
              exit 1
            else
              exit 0
            fi
      - run:
          name: Publish release on Splunkbase
          command: |
            SPLUNKBASE_SESSION_ID=$(awk '/id/{printf $1}' login.xml | cut -d">" -f2 | cut -d"<" -f1)
            curl --location --request POST 'https://splunkbase.splunk.com/api/v1/app/'"${SPLUNKBASE_APP_ID}"'/new_release/' --header 'Authorization: Basic ZGlvZ29mZ206cHVmcFloLWd5cWZ1Ny13dW5oeWQ=' --header 'Cookie: sessionid='"$SPLUNKBASE_SESSION_ID"''; csrftoken=sMucg13V1Ul7v7JNlQLPzjr3fFbZFpHQmNwW4wvnFfJXrVXbvKUaG6lzCGPi48tM' --form 'files[]=@/'"${CIRCLE_PROJECT_REPONAME}"'/dist' --form 'filename='"${CIRCLE_PROJECT_REPONAME}"'.tgz' --form 'cim_versions=4.9,4.7' --form 'splunk_versions=8.0' --form 'visibility=true'
            exit 1

workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - validate-content:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - validate-content
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-splunkbase-release:
          context: GitHub
          requires:
            - validate-content
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master